# Generated by Django 4.1 on 2022-09-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0004_alter_project_labelprefix_alter_project_wikiprefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enableExports',
            field=models.BooleanField(default=True, help_text='Allow users to download contents of this project'),
        ),
    ]
