# Generated by Django 4.1 on 2022-09-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0005_project_enableexports'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enableAddComments',
            field=models.BooleanField(default=True, help_text='Allow customers to create new comments'),
        ),
    ]
