# Generated by Django 4.1 on 2022-09-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0006_project_enableaddcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='showSystemNotes',
            field=models.BooleanField(default=True, help_text='Show system notes together wir comments'),
        ),
    ]
