# Generated by Django 4.1 on 2022-08-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='assignees',
            field=models.ManyToManyField(blank=True, to='userinterface.teammember'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
