# Generated by Django 4.1 on 2022-09-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0002_project_image_alter_project_assignees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='labelPrefix',
            field=models.CharField(default='', help_text="User are not allowed to create issues with labels that don't start with this prefix", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='wikiPrefix',
            field=models.CharField(default='', help_text="User are not allowed to view wiki pages with paths that don't start with this prefix", max_length=500),
            preserve_default=False,
        ),
    ]
