# Generated by Django 4.1 on 2022-09-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0007_project_showsystemnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='homepage',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
