# Generated by Django 4.1 on 2022-09-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0008_teammember_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='homepage',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
