# Generated by Django 4.1 on 2022-10-25 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0010_alter_teammember_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('offer', 'Offers'), ('invoice', 'Invoices'), ('contract', 'Contracts'), ('privacy', 'Privacy'), ('draft', 'Drafts'), ('documentation', 'Documentation'), ('other', 'Other')], max_length=200)),
                ('file', models.FileField(upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinterface.project')),
            ],
        ),
    ]
