# Generated by Django 4.1 on 2022-10-26 10:52

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0011_downloadablefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadablefile',
            name='date',
            field=models.DateField(default=datetime(2022,1,1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downloadablefile',
            name='category',
            field=models.CharField(choices=[('client', 'Customer data'), ('offer', 'Offers'), ('invoice', 'Invoices'), ('contract', 'Contracts'), ('privacy', 'Privacy'), ('draft', 'Drafts'), ('documentation', 'Documentation'), ('other', 'Other')], max_length=200),
        ),
    ]
