# Generated by Django 4.1 on 2022-10-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0013_project_publicoverviewpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='privateUrlHash',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
