# Generated by Django 4.1 on 2022-10-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0015_project_publicoverviewtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadablefile',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downloadablefile',
            name='category',
            field=models.IntegerField(choices=[(0, 'Customer data'), (10, 'Offers'), (20, 'Draft'), (30, 'Orders'), (40, 'Contracts'), (50, 'Privacy documents'), (60, 'Invoices'), (70, 'Documentation'), (80, 'Other')], max_length=200),
        ),
    ]
