# Generated by Django 4.1 on 2022-10-28 09:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0017_alter_project_publicoverviewpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publicOverviewText',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
