# Generated by Django 4.1 on 2022-11-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0018_alter_project_publicoverviewtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closed',
            field=models.BooleanField(default=False, help_text='If closed a project is no longer accessible or visible'),
        ),
    ]
