# Generated by Django 4.1 on 2022-11-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0019_project_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadablefile',
            name='link',
            field=models.CharField(blank=True, help_text='Link to a file or document - must not be set if a file is present', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='downloadablefile',
            name='file',
            field=models.FileField(blank=True, help_text='A downloadable file - must not be added if a link is set', null=True, upload_to=''),
        ),
    ]
