# Generated by Django 4.1.2 on 2022-12-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0022_project_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='firstEMailAdress',
            field=models.CharField(default=None, help_text='first notification eMail-Address if a costumer added a new  ticket', max_length=100, null=True),
        ),
    ]
