# Generated by Django 4.1.2 on 2023-07-24 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0024_remove_project_firstemailadress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notificationLastRun',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='repositoryService',
            field=models.IntegerField(choices=[(1, 'GitLab'), (2, 'GitHub')], default=1),
        ),
        migrations.AddField(
            model_name='userprojectassignment',
            name='enableNotifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='downloadablefile',
            name='category',
            field=models.IntegerField(choices=[(-1, 'Important Files & Links'), (0, 'Customer data'), (10, 'Offers'), (20, 'Draft'), (30, 'Orders'), (40, 'Contracts'), (50, 'Privacy documents'), (60, 'Invoices'), (64, 'Development'), (65, 'Production'), (70, 'Documentation'), (80, 'Other')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='firstEMailAddress',
            field=models.CharField(default=None, help_text='E-Mail Address that gets notified if a new ticket is created by the customer', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='inactive',
            field=models.BooleanField(default=False, help_text='Inactive project are marked as inactive and not shown in the overview'),
        ),
    ]
