# Generated by Django 4.2.16 on 2024-10-08 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userinterface', '0025_project_notificationlastrun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='enableAddComments',
            new_name='enable_add_comments',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='enableDocumentation',
            new_name='enable_documentation',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='enableExports',
            new_name='enable_exports',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='enableTicketCreation',
            new_name='enable_ticket_creation',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='firstEMailAddress',
            new_name='first_email_address',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='notificationLastRun',
            new_name='notification_last_run',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='privateUrlHash',
            new_name='private_url_hash',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projectIdentifier',
            new_name='project_identifier',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='publicOverviewPassword',
            new_name='public_overview_password',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='publicOverviewText',
            new_name='public_overview_text',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='repositoryService',
            new_name='repository_service',
        ),
        migrations.RenameField(
            model_name='userprojectassignment',
            old_name='accessToken',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='userprojectassignment',
            old_name='enableNotifications',
            new_name='enable_notifications',
        ),
        migrations.RemoveField(
            model_name='project',
            name='enableMilestones',
        ),
        migrations.RemoveField(
            model_name='project',
            name='labelPrefix',
        ),
        migrations.RemoveField(
            model_name='project',
            name='showSystemNotes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='wikiPrefix',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='username',
        ),
        migrations.AddField(
            model_name='project',
            name='enable_milestones',
            field=models.BooleanField(default=True, help_text='Visualize milestones and create a Gantt chart'),
        ),
        migrations.AddField(
            model_name='project',
            name='label_prefix',
            field=models.CharField(blank=True, help_text="Users are not allowed to create issues with labels that don't start with this prefix", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='show_system_notes',
            field=models.BooleanField(default=True, help_text='Show system notes together with comments'),
        ),
        migrations.AddField(
            model_name='project',
            name='wiki_prefix',
            field=models.CharField(blank=True, help_text="Users are not allowed to view wiki pages with paths that don't start with this prefix", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teammember',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='closed',
            field=models.BooleanField(default=False, help_text='If closed, a project is no longer accessible or visible'),
        ),
        migrations.AlterField(
            model_name='project',
            name='inactive',
            field=models.BooleanField(default=False, help_text='Inactive projects are marked as inactive and not shown in the overview'),
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_notifications', models.BooleanField(default=False)),
                ('can_handle_contracts', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinterface.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userinterface.team'),
            preserve_default=False,
        ),
    ]
