# Generated by Django 4.2.16 on 2024-10-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0030_alter_company_options_alter_customeruser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprojectassignment',
            options={'verbose_name': 'Projektzuweisung', 'verbose_name_plural': 'Projektzuweisungen'},
        ),
    ]
