# Generated by Django 4.2.16 on 2024-10-08 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userinterface', '0031_alter_userprojectassignment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojectassignment',
            name='teams',
            field=models.ManyToManyField(blank=True, to='userinterface.team'),
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.AlterField(
            model_name='userprojectassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ManyToManyField(blank=True, to='userinterface.team'),
        ),
    ]
