# Generated by Django 4.2.16 on 2024-10-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0032_userprojectassignment_teams_remove_teammember_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, choices=[('TL', 'Teamleitung'), ('DEV', 'Developer'), ('ORG', 'Organisation')], max_length=3),
        ),
    ]
