# Generated by Django 4.2.16 on 2024-10-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0033_alter_teammember_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='repository_service',
            new_name='repositoryService',
        ),
    ]
