# Generated by Django 4.2.16 on 2024-10-09 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0034_rename_repository_service_project_repositoryservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Kundenunternehmen', 'verbose_name_plural': 'Kundenunternehmen'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'SD Team', 'verbose_name_plural': 'SD Teams'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'SD Teammitglied', 'verbose_name_plural': 'SD Teammitglieder'},
        ),
        migrations.RemoveField(
            model_name='userprojectassignment',
            name='user',
        ),
        migrations.AddField(
            model_name='userprojectassignment',
            name='customer_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userinterface.company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repositoryService',
            field=models.IntegerField(choices=[(1, 'GitLab'), (2, 'GitHub')], default=2),
        ),
    ]
