# Generated by Django 4.2.16 on 2024-10-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0035_alter_company_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='CustomerCompany',
        ),
    ]
