# Generated by Django 4.2.16 on 2024-10-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0036_rename_company_customercompany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='company',
            new_name='customer_company',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='company',
            new_name='customer_company',
        ),
    ]
