# Generated by Django 4.2.16 on 2024-10-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0037_rename_company_customeruser_customer_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='assignees',
            new_name='teams',
        ),
    ]
