# Generated by Django 4.2.16 on 2024-10-09 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0038_rename_assignees_project_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='repositoryService',
            new_name='repository_service',
        ),
        migrations.AlterField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(blank=True, to='userinterface.team'),
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.AlterField(
            model_name='userprojectassignment',
            name='customer_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinterface.customercompany'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='userinterface.team'),
        ),
    ]
