# Generated by Django 4.2.16 on 2024-10-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0039_rename_repositoryservice_project_repository_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='access_token',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
