# Generated by Django 4.2.16 on 2024-10-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0040_project_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(blank=True, to='userinterface.teammember'),
        ),
    ]
