# Generated by Django 4.2.16 on 2024-10-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0042_alter_project_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercompany',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
