# Generated by Django 4.2.16 on 2024-10-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0043_customercompany_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercompany',
            name='image',
            field=models.ImageField(blank=True, upload_to='project_images/'),
        ),
    ]
