# Generated by Django 4.2.16 on 2024-10-09 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userinterface', '0044_alter_customercompany_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.AddField(
            model_name='teammember',
            name='teams',
            field=models.ManyToManyField(related_name='members', to='userinterface.team'),
        ),
        migrations.AlterField(
            model_name='customercompany',
            name='image',
            field=models.ImageField(blank=True, upload_to='customer_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
